import './globals.css'
import {Inter} from 'next/font/google'
import Link from "next/link";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <div className="container mx-auto mt-10">
            <div className="flex gap-10">
                <div className="border border-gray-300 rounded-md w-1/3 p-3">
                    <div>
                        <Link href="/users/profile/page">Feed</Link>
                    </div>
                    <div>
                        <Link href="/users/profile/page">Profile</Link>
                    </div>
                    <div>
                        <Link href="/users/profile/page">Posts</Link>
                    </div>
                </div>
                <div>
                    {children}
                </div>
            </div>
        </div>
        </body>
        </html>
    )
}
